GUI Addition
frtru/GemParticles pull request #43
Opened 2017-03-07 03:56 UTC by larivierec

The GemParticles can now make use of the classes in AntTweakBar.
Using this library we will be able to modify OpenGL properties during runtime.

The application will compile AntTweakBar and link it against the application.
If sources are needed, they may be included within the GemParticles application.

2017-03-07 23:53 UTC, frtru commented
Can't merge, gotta fix conflicts first. But, how is GemParticlesGUI going to use entities from GemParticles? Is GemParticlesGUI going to define stricly helper classes/functions for us to call in GemParticles?

2017-03-08 00:28 UTC, frtru reviewed
Everything looks good, but I'd to keep the VS files just as backup for now.

2017-03-08 01:43 UTC, larivierec commented
i'll have to update the cmake files first. until then this shouldn't be merged.

2017-03-10 03:32 UTC, larivierec commented
https://github.com/lighttransport/nanogi/blob/master/cmake/FindGLFW.cmake 

https://github.com/nvpro-samples/shared_sources/blob/master/cmake/FindGLFW.cmake

Use these as a reference 
for CPU architecture

2017-03-17 03:22 UTC, frtru requested changes
I'd rather keep the VS files and I'll update them so that they can coexist and not affect the code. The reason is that, I don't think it works the way I would expect it to work on windows and it would be too much troubles to add a file to the cmakelists.txt and regenerate the visual studio files each time, since right now I have to manually edit a bunch of variables that give me errors even though I have the XXX_HOME variables defined. Even with that I have some weird compilation/linking errors. 

So just re-add the VS files, delete particle_system.cc and we're good to go :)

2017-03-17 03:22 UTC, frtru commented on src/particle_system.cc
> +/*************************************************************************
You can remove this file, it is not needed anymore. Everything is in .hh, because of templates.

2017-03-17 12:39 UTC, merged